server:
  port: 8081

logging:
  level:
    org.springframework: debug

spring:
  jpa:
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match:
    - /**

management:
  endpoints:
    web:
      exposure:
        include: "*"
